apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor 
metadata: 
  name: interface-status-monitor 
  namespace: monitoring 
  labels: 
    release: monitoring
spec: 
  selector: 
    matchLabels: 
      app: interface-status 
  endpoints: 
  - port: metrics 
    interval: 15s 
  namespaceSelector: 
    matchNames: 
    - default 